//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SII_Entities : DbContext
    {
        public SII_Entities()
            : base("name=SII_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Acta> Tbl_Acta { get; set; }
        public virtual DbSet<Tbl_Acta_Usuario> Tbl_Acta_Usuario { get; set; }
        public virtual DbSet<Tbl_Agremiado> Tbl_Agremiado { get; set; }
        public virtual DbSet<Tbl_Compania> Tbl_Compania { get; set; }
        public virtual DbSet<Tbl_Deduccion> Tbl_Deduccion { get; set; }
        public virtual DbSet<Tbl_Departamento> Tbl_Departamento { get; set; }
        public virtual DbSet<Tbl_Empleado> Tbl_Empleado { get; set; }
        public virtual DbSet<Tbl_EstadoCivil> Tbl_EstadoCivil { get; set; }
        public virtual DbSet<Tbl_Gestion> Tbl_Gestion { get; set; }
        public virtual DbSet<Tbl_Persona> Tbl_Persona { get; set; }
        public virtual DbSet<Tbl_Rol> Tbl_Rol { get; set; }
        public virtual DbSet<Tbl_TipoGestion> Tbl_TipoGestion { get; set; }
        public virtual DbSet<Tbl_TipoUsuario> Tbl_TipoUsuario { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
    }
}
