//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gestion
    {
        public int id_Gestion { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fecha_Inicio { get; set; }
        public Nullable<System.DateTime> fecha_Fin { get; set; }
        public int id_Empleado { get; set; }
        public int id_TipoGestion { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> fecha_Ausencia { get; set; }
    
        public virtual Tbl_Empleado Tbl_Empleado { get; set; }
        public virtual Tbl_TipoGestion Tbl_TipoGestion { get; set; }
    }
}
