//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Deduccion
    {
        public int id_Deduccion { get; set; }
        public System.DateTime fecha_Deduccion { get; set; }
        public decimal monto { get; set; }
        public int id_Agremiado { get; set; }
        public int estado { get; set; }
    
        public virtual Tbl_Agremiado Tbl_Agremiado { get; set; }
    }
}
