//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Persona()
        {
            this.Tbl_Usuario = new HashSet<Tbl_Usuario>();
        }
    
        public int id_Persona { get; set; }
        public int cedula { get; set; }
        public string nombre { get; set; }
        public string primer_Apellido { get; set; }
        public string segundo_Apellido { get; set; }
        public string genero { get; set; }
        public string nacionalidad { get; set; }
        public int id_ECivil { get; set; }
        public System.DateTime fecha_Nac { get; set; }
        public System.DateTime fecha_Reg { get; set; }
        public int telefono { get; set; }
        public string direccion { get; set; }
        public string correo_Electronico { get; set; }
        public int estado { get; set; }
    
        public virtual Tbl_EstadoCivil Tbl_EstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Usuario> Tbl_Usuario { get; set; }
    }
}
